// packages/svelte/test-app/Pages/Flash/InitialFlash.svelte
<script lang="ts">
  import { page, router } from '@inertiajs/svelte'

  let flashEvents: Record<string, unknown>[] = []

  router.on('flash', (e) => {
    flashEvents = [...flashEvents, e.detail.flash]
  })
</script>

<div>
  <span id="flash">{$page.flash ? JSON.stringify($page.flash) : 'no-flash'}</span>
  <span id="flash-events">{JSON.stringify(flashEvents)}</span>
</div>

// packages/vue3/test-app/Pages/Flash/InitialFlash.vue
<script setup lang="ts">
import { router, usePage } from '@inertiajs/vue3'
import { ref } from 'vue'

const page = usePage()
const flashEvents = ref<Record<string, unknown>[]>([])

router.on('flash', (e) => {
  flashEvents.value.push(e.detail.flash)
})
</script>

<template>
  <div>
    <span id="flash">{{ page.flash ? JSON.stringify(page.flash) : 'no-flash' }}</span>
    <span id="flash-events">{{ JSON.stringify(flashEvents) }}</span>
  </div>
</template>
