// packages/vue3/test-app/Pages/Users/Index.vue
<script setup>
import { Link } from '@inertiajs/vue3'

defineProps({
  users: Array,
})
</script>

<template>
  <div>
    <h1>Users Index</h1>
    <ul>
      <li v-for="user in users" :key="user.id">
        <Link :href="`/remember/users/${user.id}/edit?remember=true`">Edit {{ user.name }}</Link>
      </li>
    </ul>
  </div>
</template>

// packages/react/test-app/Pages/Users/Index.tsx
import { Link } from '@inertiajs/react'

interface User {
  id: number
  name: string
  email: string
}

export default ({ users }: { users: User[] }) => {
  return (
    <div>
      <h1>Users Index</h1>
      <ul>
        {users.map((user) => (
          <li key={user.id}>
            <Link href={`/remember/users/${user.id}/edit?remember=true`}>Edit {user.name}</Link>
          </li>
        ))}
      </ul>
    </div>
  )
}
