// packages/vue3/test-app/Pages/DeferredProps/InstantReload.vue
<script setup lang="ts">
import { Deferred, router } from '@inertiajs/vue3'
import { onMounted } from 'vue'

defineProps<{
  foo?: { text: string }
  bar?: { text: string }
}>()

onMounted(() => {
  router.reload({
    only: ['foo'],
  })
})
</script>

<template>
  <Deferred data="foo">
    <template #fallback>
      <div>Loading foo...</div>
    </template>
    <div>{{ foo?.text }}</div>
  </Deferred>

  <Deferred data="bar">
    <template #fallback>
      <div>Loading bar...</div>
    </template>
    <div>{{ bar?.text }}</div>
  </Deferred>
</template>

// packages/react/test-app/Pages/DeferredProps/InstantReload.tsx
import { Deferred, router } from '@inertiajs/react'
import { useEffect } from 'react'

export default ({ foo, bar }: { foo?: { text: string }; bar?: { text: string } }) => {
  useEffect(() => {
    router.reload({
      only: ['foo'],
    })
  }, [])

  return (
    <>
      <Deferred data="foo" fallback={<div>Loading foo...</div>}>
        <div>{foo?.text}</div>
      </Deferred>

      <Deferred data="bar" fallback={<div>Loading bar...</div>}>
        <div>{bar?.text}</div>
      </Deferred>
    </>
  )
}
