// packages/svelte5/test-app/Pages/DeferredProps/ManyGroups.svelte
<script lang="ts">
  import { Deferred, inertia } from '@inertiajs/svelte5'

  const { foo, bar, baz, qux, quux }: {
    foo?: { text: string };
    bar?: { text: string };
    baz?: { text: string };
    qux?: { text: string };
    quux?: { text: string };
  } = $props()
</script>

<Deferred data="foo">
  {foo?.text}
  {#snippet fallback()}
    <div>Loading foo...</div>
  {/snippet}
</Deferred>

<Deferred data="bar">
  {bar?.text}
  {#snippet fallback()}
    <div>Loading bar...</div>
  {/snippet}
</Deferred>

<Deferred data="baz">
  {baz?.text}
  {#snippet fallback()}
    <div>Loading baz...</div>
  {/snippet}
</Deferred>

<Deferred data="qux">
  {qux?.text}
  {#snippet fallback()}
    <div>Loading qux...</div>
  {/snippet}
</Deferred>

<Deferred data="quux">
  {quux?.text}
  {#snippet fallback()}
    <div>Loading quux...</div>
  {/snippet}
</Deferred>

<a href="/deferred-props/page-1" use:inertia>Page 1</a>
<a href="/deferred-props/page-2" use:inertia>Page 2</a>
<a href="/deferred-props/many-groups" use:inertia>Many groups</a>

// packages/react/test-app/Pages/DeferredProps/ManyGroups.tsx
import { Deferred, Link, usePage } from '@inertiajs/react'

export default () => {
  const { foo, bar, baz, qux, quux } = usePage<{
    foo?: { text: string }
    bar?: { text: string }
    baz?: { text: string }
    qux?: { text: string }
    quux?: { text: string }
  }>().props

  return (
    <>
      <Deferred data="foo" fallback={<div>Loading foo...</div>}>
        {foo?.text}
      </Deferred>

      <Deferred data="bar" fallback={() => <div>Loading bar...</div>}>
        {() => bar?.text}
      </Deferred>

      <Deferred data="baz" fallback={<div>Loading baz...</div>}>
        {baz?.text}
      </Deferred>

      <Deferred data="qux" fallback={() => <div>Loading qux...</div>}>
        {() => qux?.text}
      </Deferred>

      <Deferred data="quux" fallback={<div>Loading quux...</div>}>
        {quux?.text}
      </Deferred>

      <Link href="/deferred-props/page-1">Page 1</Link>
      <Link href="/deferred-props/page-2">Page 2</Link>
      <Link href="/deferred-props/many-groups">Many groups</Link>
    </>
  )
}
