// packages/svelte/test-app/Pages/DeferredProps/WithCallback.svelte
<script lang="ts">
  import { Deferred, inertia } from '@inertiajs/svelte'

  export let foo: { text: string } | undefined
  export let bar: { text: string } | undefined
</script>

<Deferred data="foo" let:loading>
  {#if loading}
    <div>Loading foo (callback)...</div>
  {:else}
    {foo?.text}
  {/if}
</Deferred>

<Deferred data="bar" let:loading>
  {#if loading}
    <div>Loading bar (callback)...</div>
  {:else}
    {bar?.text}
  {/if}
</Deferred>

<a href="/deferred-props/page-1" use:inertia>Page 1</a>
<a href="/deferred-props/page-2" use:inertia>Page 2</a>

// packages/react/test-app/Pages/DeferredProps/WithCallback.tsx
import { Deferred, Link, usePage } from '@inertiajs/react'

const Foo = () => {
  const { foo } = usePage<{ foo?: { text: string } }>().props

  return foo?.text
}

const Bar = () => {
  const { bar } = usePage<{ bar?: { text: string } }>().props

  return bar?.text
}

export default () => {
  return (
    <>
      <Deferred data="foo">{({ loading }) => (loading ? <div>Loading foo (callback)...</div> : <Foo />)}</Deferred>

      <Deferred data="bar">{({ loading }) => (loading ? <div>Loading bar (callback)...</div> : <Bar />)}</Deferred>

      <Link href="/deferred-props/page-1">Page 1</Link>
      <Link href="/deferred-props/page-2">Page 2</Link>
    </>
  )
}
