// packages/vue3/test-app/Pages/FormComponent/Context/Methods.vue
<script setup lang="ts">
import { Form } from '@inertiajs/vue3'
import MethodsTestComponent from './MethodsTestComponent.vue'
</script>

<template>
  <Form action="/form-component/context/methods" method="post" #default="{ errors }">
    <pre v-if="Object.keys(errors).length">{{ JSON.stringify(errors, null, 2) }}</pre>

    <input type="text" name="name" value="Initial Name" />
    <input type="email" name="email" value="initial@example.com" />
    <textarea name="bio">Initial bio</textarea>

    <MethodsTestComponent />
  </Form>
</template>

// packages/svelte/test-app/Pages/FormComponent/Context/Methods.svelte
<script lang="ts">
  import { Form } from '@inertiajs/svelte'
  import MethodsTestComponent from './MethodsTestComponent.svelte'
</script>

<Form action="/form-component/context/methods" method="post" let:errors>
  {#if Object.keys(errors).length}<pre>{JSON.stringify(errors, null, 2)}</pre>{/if}

  <input type="text" name="name" value="Initial Name" />
  <input type="email" name="email" value="initial@example.com" />
  <textarea name="bio">Initial bio</textarea>

  <MethodsTestComponent />
</Form>
