// packages/vue3/test-app/Pages/HttpCancellation.vue
<script setup lang="ts">
import { http, router } from '@inertiajs/vue3'
import { ref } from 'vue'

declare global {
  interface Window {
    _http_cancellation_log: string[]
  }
}

window._http_cancellation_log = []

const messages = ref<string[]>([])

const log = (message: string) => {
  window._http_cancellation_log.push(message)
  messages.value = [...window._http_cancellation_log]
}

const requestWithAbortedSignal = async () => {
  const controller = new AbortController()
  const off = http.onError((error) => log(`error:${error.name}`))

  controller.abort()

  try {
    await http.getClient().request({ method: 'get', url: '/dump/get?request=aborted', signal: controller.signal })
    log('outcome:resolved')
  } catch (error) {
    log(`outcome:${(error as Error).name}`)
  } finally {
    off()
  }
}

const cancelDuringPreparation = async () => {
  const controller = new AbortController()

  let release!: () => void
  let entered!: () => void
  const blocked = new Promise<void>((resolve) => (release = resolve))
  const started = new Promise<void>((resolve) => (entered = resolve))

  const off = http.onRequest(async (config) => {
    entered()
    await blocked

    return config
  })

  const outcome = http
    .getClient()
    .request({ method: 'get', url: '/dump/get?request=preparing', signal: controller.signal })
    .then(
      () => 'resolved',
      (error: Error) => error.name,
    )

  await started
  controller.abort()
  release()

  log(`outcome:${await outcome}`)
  off()
}

let startedController: AbortController | null = null

const startLongRequest = async () => {
  startedController = new AbortController()

  const outcome = await http
    .getClient()
    .request({ method: 'get', url: '/dump/get?request=started', signal: startedController.signal })
    .then(
      () => 'resolved',
      (error: Error) => error.name,
    )

  log(`outcome:${outcome}`)
}

const cancelStartedRequest = () => {
  startedController?.abort()
  startedController = null
}

const visitCancelledBeforeSend = () => {
  router.visit('/dump/get?request=old', {
    async: true,
    onCancelToken: (token) => token.cancel(),
    onCancel: () => log('old:cancel'),
    onFinish: () => log('old:finish'),
    onSuccess: () => log('old:success'),
  })

  router.visit('/dump/get?request=current', {
    async: true,
    onSuccess: () => log('current:success'),
  })
}

const prefetchCancelledBeforeSend = () => {
  let off: () => void = () => {}

  off = http.onError((error) => {
    log(`prefetch:${error.name}`)
    off()
  })

  router.prefetch('/dump/get?request=prefetch', { onCancelToken: (token) => token.cancel() })
}
</script>

<template>
  <div>
    <h1>HTTP Cancellation</h1>

    <button @click="requestWithAbortedSignal">Request With Aborted Signal</button>
    <button @click="cancelDuringPreparation">Cancel During Preparation</button>
    <button @click="startLongRequest">Start Long Request</button>
    <button @click="cancelStartedRequest">Cancel Started Request</button>
    <button @click="visitCancelledBeforeSend">Visit Cancelled Before Send</button>
    <button @click="prefetchCancelledBeforeSend">Prefetch Cancelled Before Send</button>

    <div>
      Log: <span id="log">{{ messages.join(',') }}</span>
    </div>
  </div>
</template>

// packages/react/test-app/Pages/HttpCancellation.tsx
import { http, router } from '@inertiajs/react'
import { useEffect, useState } from 'react'

declare global {
  interface Window {
    _http_cancellation_log: string[]
  }
}

export default () => {
  const [messages, setMessages] = useState<string[]>([])

  useEffect(() => {
    window._http_cancellation_log = []
  }, [])

  const log = (message: string) => {
    window._http_cancellation_log.push(message)
    setMessages([...window._http_cancellation_log])
  }

  const requestWithAbortedSignal = async () => {
    const controller = new AbortController()
    const off = http.onError((error) => log(`error:${error.name}`))

    controller.abort()

    try {
      await http.getClient().request({ method: 'get', url: '/dump/get?request=aborted', signal: controller.signal })
      log('outcome:resolved')
    } catch (error) {
      log(`outcome:${(error as Error).name}`)
    } finally {
      off()
    }
  }

  const cancelDuringPreparation = async () => {
    const controller = new AbortController()

    let release!: () => void
    let entered!: () => void
    const blocked = new Promise<void>((resolve) => (release = resolve))
    const started = new Promise<void>((resolve) => (entered = resolve))

    const off = http.onRequest(async (config) => {
      entered()
      await blocked

      return config
    })

    const outcome = http
      .getClient()
      .request({ method: 'get', url: '/dump/get?request=preparing', signal: controller.signal })
      .then(
        () => 'resolved',
        (error: Error) => error.name,
      )

    await started
    controller.abort()
    release()

    log(`outcome:${await outcome}`)
    off()
  }

  let startedController: AbortController | null = null

  const startLongRequest = async () => {
    startedController = new AbortController()

    const outcome = await http
      .getClient()
      .request({ method: 'get', url: '/dump/get?request=started', signal: startedController.signal })
      .then(
        () => 'resolved',
        (error: Error) => error.name,
      )

    log(`outcome:${outcome}`)
  }

  const cancelStartedRequest = () => {
    startedController?.abort()
    startedController = null
  }

  const visitCancelledBeforeSend = () => {
    router.visit('/dump/get?request=old', {
      async: true,
      onCancelToken: (token) => token.cancel(),
      onCancel: () => log('old:cancel'),
      onFinish: () => log('old:finish'),
      onSuccess: () => log('old:success'),
    })

    router.visit('/dump/get?request=current', {
      async: true,
      onSuccess: () => log('current:success'),
    })
  }

  const prefetchCancelledBeforeSend = () => {
    let off: () => void = () => {}

    off = http.onError((error) => {
      log(`prefetch:${error.name}`)
      off()
    })

    router.prefetch('/dump/get?request=prefetch', { onCancelToken: (token) => token.cancel() })
  }

  return (
    <div>
      <h1>HTTP Cancellation</h1>

      <button onClick={requestWithAbortedSignal}>Request With Aborted Signal</button>
      <button onClick={cancelDuringPreparation}>Cancel During Preparation</button>
      <button onClick={startLongRequest}>Start Long Request</button>
      <button onClick={cancelStartedRequest}>Cancel Started Request</button>
      <button onClick={visitCancelledBeforeSend}>Visit Cancelled Before Send</button>
      <button onClick={prefetchCancelledBeforeSend}>Prefetch Cancelled Before Send</button>

      <div>
        Log: <span id="log">{messages.join(',')}</span>
      </div>
    </div>
  )
}
