// packages/react/test-app/Pages/History/NonSerializableTarget.tsx
import { router } from '@inertiajs/react'

export default ({ message }: { message: string }) => {
  const clientVisit = () => {
    router.push({
      url: '/history/non-serializable/landed',
      component: 'History/NonSerializableTarget',
      props: { message: 'Client visit landed' },
    })
  }

  return (
    <>
      <button onClick={clientVisit}>Client visit</button>

      <div>{message}</div>
    </>
  )
}

// packages/svelte/test-app/Pages/History/NonSerializableTarget.svelte
<script lang="ts">
  import { router } from '@inertiajs/svelte'

  interface Props {
    message: string
    onAction?: () => string
  }

  let { message }: Props = $props()

  const clientVisit = () => {
    router.push({
      url: '/history/non-serializable/landed',
      component: 'History/NonSerializableTarget',
      props: { message: 'Client visit landed' },
    })
  }
</script>

<button onclick={clientVisit}>Client visit</button>

<div>{message}</div>
