// packages/react/test-app/Pages/NestedProps/WhenVisible.tsx
import { WhenVisible, usePage } from '@inertiajs/react'

const Visitors = () => {
  const { stats } = usePage<{ stats?: { visitors: number } }>().props

  return <p id="visitors">Visitors: {stats?.visitors}</p>
}

export default () => {
  return (
    <div style={{ marginTop: '2000px', padding: '20px' }}>
      <WhenVisible data="stats.visitors" fallback={<p id="loading">Loading visitors...</p>}>
        <Visitors />
      </WhenVisible>
    </div>
  )
}

// packages/svelte/test-app/Pages/NestedProps/WhenVisible.svelte
<script lang="ts">
  import { WhenVisible } from '@inertiajs/svelte'

  interface Props {
    stats?: {
      visitors: number
    }
  }

  let { stats = undefined }: Props = $props()
</script>

<div style="margin-top: 2000px; padding: 20px">
  <WhenVisible data="stats.visitors">
    {#snippet fallback()}
      <p id="loading">Loading visitors...</p>
    {/snippet}

    <p id="visitors">Visitors: {stats?.visitors}</p>
  </WhenVisible>
</div>
