// packages/svelte/test-app/Pages/FormComponent/ResetAttributes/ResetOnSuccess.svelte
<script lang="ts">
  import { Form } from '@inertiajs/svelte'
</script>

<Form method="post" action="/form-component/reset-on-success" resetOnSuccess let:errors>
  <div>
    <label for="name">Name</label>
    <input type="text" name="name" id="name" value="John Doe" />
    <p id="error_name">{errors.name || ''}</p>
  </div>

  <div>
    <label for="email">Email</label>
    <input type="email" name="email" id="email" value="john@doe.biz" />
    <p id="error_email">{errors.email || ''}</p>
  </div>

  <button type="submit">Submit</button>
</Form>

// packages/react/test-app/Pages/FormComponent/ResetAttributes/ResetOnSuccess.tsx
import { Form } from '@inertiajs/react'

export default () => {
  return (
    <div>
      <h1>Reset On Success Test</h1>

      <Form method="post" action="/form-component/reset-on-success" resetOnSuccess>
        {({ errors }) => (
          <>
            <div>
              <label htmlFor="name">Name</label>
              <input type="text" name="name" id="name" defaultValue="John Doe" />
              {errors.name && <p id="error_name">{errors.name}</p>}
            </div>

            <div>
              <label htmlFor="email">Email</label>
              <input type="email" name="email" id="email" defaultValue="john@doe.biz" />
              {errors.email && <p id="error_email">{errors.email}</p>}
            </div>

            <button type="submit">Submit</button>
          </>
        )}
      </Form>
    </div>
  )
}
