// playgrounds/react/resources/js/Components/Layout.jsx
import { Link, usePage } from '@inertiajs/react'

export default function Layout({ children }) {
  const { appName } = usePage().props

  return (
    <>
      <nav className="flex items-center space-x-6 bg-slate-800 px-10 py-6 text-white">
        <div className="rounded-lg bg-slate-700 px-4 py-1">{appName}</div>
        <Link href="/" className="hover:underline">
          Home
        </Link>
        <Link href="/users" className="hover:underline">
          Users
        </Link>
        <Link href="/article" className="hover:underline">
          Article
        </Link>
        <Link href="/form" className="hover:underline">
          Form
        </Link>
        <Link href="/logout" method="post" as="button" type="button" className="hover:underline">
          Logout
        </Link>
      </nav>
      <main className="px-10 py-8">{children}</main>
    </>
  )
}

// playgrounds/vue3/resources/js/Components/Layout.vue
<script setup>
import { Link, usePage } from '@inertiajs/vue3'
import { computed } from 'vue'

const appName = computed(() => usePage().props.value.appName)
</script>

<template>
  <nav class="flex items-center space-x-6 bg-slate-800 px-10 py-6 text-white">
    <div class="rounded-lg bg-slate-700 px-4 py-1">{{ appName }}</div>
    <Link href="/" class="hover:underline">Home</Link>
    <Link href="/users" class="hover:underline">Users</Link>
    <Link href="/article" class="hover:underline">Article</Link>
    <Link href="/form" class="hover:underline">Form</Link>
    <Link href="/logout" method="post" as="button" type="button" class="hover:underline">Logout</Link>
  </nav>
  <main class="px-10 py-8">
    <slot />
  </main>
</template>
