// packages/react/test-app/Pages/FormHelper/TypeScript/Generic.tsx
// This component is used for checking the TypeScript implementation; there is no Playwright test depending on it.
import type { FormDataConvertible } from '@inertiajs/core'
import type { InertiaFormProps } from '@inertiajs/react'

interface GenericProps<TFormData extends Record<string, FormDataConvertible>> {
  form: InertiaFormProps<TFormData>
}

export default function Generic<TFormData extends Record<string, FormDataConvertible>>({
  form
}: GenericProps<TFormData>) {
  return (
    <div>
      {/* Generic form component */}
    </div>
  )
}

// packages/vue3/test-app/Pages/FormHelper/TypeScript/Generic.vue
<script setup lang="ts" generic="TFormData extends Record<string, FormDataConvertible>">
// This component is used for checking the TypeScript implementation; there is no Playwright test depending on it.
import type { FormDataConvertible } from '@inertiajs/core'
import type { InertiaForm } from '@inertiajs/vue3'

const props = defineProps<{
  form: InertiaForm<TFormData>
}>()
</script>
