// packages/svelte/test-app/Pages/Layers/Deferred.svelte
<script lang="ts">
  import { Deferred } from '@inertiajs/svelte'

  let { name, stats }: { name: string; stats?: number[] } = $props()
</script>

<div>Deferred layer: {name}</div>

<Deferred data="stats">
  {#snippet fallback()}
    <div data-testid="deferred-fallback">Loading stats...</div>
  {/snippet}
  <div data-testid="deferred-stats">{stats?.join(',')}</div>
</Deferred>

// packages/react/test-app/Pages/Layers/Deferred.tsx
import { Deferred } from '@inertiajs/react'

export default ({ name, stats }: { name: string; stats?: number[] }) => (
  <>
    <div>Deferred layer: {name}</div>

    <Deferred data="stats" fallback={<div data-testid="deferred-fallback">Loading stats...</div>}>
      <div data-testid="deferred-stats">{stats?.join(',')}</div>
    </Deferred>
  </>
)
