// packages/vue3/test-app/Pages/NestedProps/Deferred.vue
<script setup lang="ts">
import { Deferred } from '@inertiajs/vue3'

defineProps<{
  auth: {
    user?: string
    notifications?: string[]
  }
}>()
</script>

<template>
  <p id="user">User: {{ auth.user }}</p>

  <Deferred data="auth.notifications">
    <template #fallback>
      <div id="loading">Loading notifications...</div>
    </template>
    <p id="notifications">Notifications: {{ auth.notifications?.join(', ') }}</p>
  </Deferred>
</template>

// packages/react/test-app/Pages/NestedProps/Deferred.tsx
import { Deferred, usePage } from '@inertiajs/react'

const Notifications = () => {
  const { auth } = usePage<{ auth: { notifications?: string[] } }>().props

  return <p id="notifications">Notifications: {auth.notifications?.join(', ')}</p>
}

export default () => {
  const { auth } = usePage<{ auth: { user?: string; notifications?: string[] } }>().props

  return (
    <>
      <p id="user">User: {auth.user}</p>

      <Deferred data="auth.notifications" fallback={<div id="loading">Loading notifications...</div>}>
        <Notifications />
      </Deferred>
    </>
  )
}
