// packages/vue3/test-app/Pages/NestedProps/SharedDotProps.vue
<script setup lang="ts">
import { router } from '@inertiajs/vue3'

defineProps<{
  auth: {
    user: {
      name: string
      email: string
      permissions?: string[]
    }
  }
}>()
</script>

<template>
  <p id="name">Name: {{ auth.user.name }}</p>
  <p id="email">Email: {{ auth.user.email }}</p>
  <p id="permissions">Permissions: {{ auth.user.permissions?.join(', ') }}</p>
  <button @click="router.reload({ only: ['auth.user.permissions'] })">Reload Permissions</button>
</template>

// packages/react/test-app/Pages/NestedProps/SharedDotProps.tsx
import { router } from '@inertiajs/react'

export default ({
  auth,
}: {
  auth: {
    user: {
      name: string
      email: string
      permissions?: string[]
    }
  }
}) => {
  return (
    <>
      <p id="name">Name: {auth.user.name}</p>
      <p id="email">Email: {auth.user.email}</p>
      <p id="permissions">Permissions: {auth.user.permissions?.join(', ')}</p>
      <button onClick={() => router.reload({ only: ['auth.user.permissions'] })}>Reload Permissions</button>
    </>
  )
}
