// packages/react/test-app/Pages/InstantVisit/Deferred.tsx
import { Deferred } from '@inertiajs/react'

export default ({ title, heavyData }: { title?: string; heavyData?: string }) => {
  return (
    <div>
      <div id="deferred">This is Deferred</div>
      <div id="title">Title: {title ?? 'none'}</div>

      <Deferred data="heavyData" fallback={<div id="heavy-loading">Loading heavy data...</div>}>
        <div id="heavy-data">Heavy: {heavyData}</div>
      </Deferred>
    </div>
  )
}

// packages/svelte/test-app/Pages/InstantVisit/Deferred.svelte
<script lang="ts">
  import { Deferred } from '@inertiajs/svelte'

  let { title, heavyData }: { title?: string; heavyData?: string } = $props()
</script>

<div>
  <div id="deferred">This is Deferred</div>
  <div id="title">Title: {title ?? 'none'}</div>

  <Deferred data="heavyData">
    {#snippet fallback()}
      <div id="heavy-loading">Loading heavy data...</div>
    {/snippet}

    <div id="heavy-data">Heavy: {heavyData}</div>
  </Deferred>
</div>
