// packages/react/test-app/Pages/Links/AutomaticCancellation.tsx
import { Link } from '@inertiajs/react'

export default () => {
  return (
    <div>
      <span className="text">This is the links page that demonstrates that only one visit can be active at a time</span>
      <Link
        href="/sleep"
        className="visit"
        onCancel={() => console.log('cancelled')}
        onStart={() => console.log('started')}
      >
        Link
      </Link>
    </div>
  )
}

// packages/svelte/test-app/Pages/Links/AutomaticCancellation.svelte
<script lang="ts">
  import { inertia } from '@inertiajs/svelte'
</script>

<div>
  <span class="text">This is the links page that demonstrates that only one visit can be active at a time</span>
  <a
    href="/sleep"
    use:inertia
    oncancel={() => console.log('cancelled')}
    onstart={() => console.log('started')}
    class="visit"
  >
    Link
  </a>
</div>
