// packages/react/test-app/Pages/Visits/Data/Object.jsx
import { router } from '@inertiajs/react'

export default (props) => {
  const visitMethod = (e) => {
    e.preventDefault()
    router.visit('/dump/get', { data: { foo: 'visit' } })
  }

  const getMethod = (e) => {
    e.preventDefault()
    router.get('/dump/get', { bar: 'get' })
  }

  const postMethod = (e) => {
    e.preventDefault()
    router.post('/dump/post', { baz: 'post' })
  }

  const putMethod = (e) => {
    e.preventDefault()
    router.put('/dump/put', { foo: 'put' })
  }

  const patchMethod = (e) => {
    e.preventDefault()
    router.patch('/dump/patch', { bar: 'patch' })
  }

  const deleteMethod = (e) => {
    e.preventDefault()
    router.delete('/dump/delete', { data: { baz: 'delete' } })
  }

  const qsafDefault = (e) => {
    e.preventDefault()
    router.visit('/dump/get', { data: { a: ['b', 'c'] } })
  }

  const qsafIndices = (e) => {
    e.preventDefault()
    router.visit('/dump/get', { data: { a: ['b', 'c'] }, queryStringArrayFormat: 'indices' })
  }

  const qsafBrackets = (e) => {
    e.preventDefault()
    router.visit('/dump/get', {
      data: { a: ['b', 'c'] },
      queryStringArrayFormat: 'brackets',
    })
  }

  const deleteQueryParam = (e) => {
    e.preventDefault()
    router.visit('/dump/get', {
      data: { a: undefined },
    })
  }

  return (
    <div>
      <span className="text">This is the page that demonstrates manual visit data passing through plain objects</span>

      <a href="#" onClick={visitMethod} className="visit">
        Visit Link
      </a>
      <a href="#" onClick={getMethod} className="get">
        GET Link
      </a>
      <a href="#" onClick={postMethod} className="post">
        POST Link
      </a>
      <a href="#" onClick={putMethod} className="put">
        PUT Link
      </a>
      <a href="#" onClick={patchMethod} className="patch">
        PATCH Link
      </a>
      <a href="#" onClick={deleteMethod} className="delete">
        DELETE Link
      </a>

      <a href="#" onClick={qsafDefault} className="qsaf-default">
        QSAF Defaults
      </a>
      <a href="#" onClick={qsafIndices} className="qsaf-indices">
        QSAF Indices
      </a>
      <a href="#" onClick={qsafBrackets} className="qsaf-brackets">
        QSAF Brackets
      </a>
      <a href="#" onClick={deleteQueryParam} className="delete-query-param">
        Delete Query Param
      </a>
    </div>
  )
}

// packages/svelte/test-app/Pages/Visits/Data/Object.svelte
<script>
  import { router } from '@inertiajs/svelte'

  const visitMethod = () => {
    router.visit('/dump/get', {
      data: { foo: 'visit' },
    })
  }

  const getMethod = () => {
    router.get('/dump/get', {
      bar: 'get',
    })
  }

  const postMethod = () => {
    router.post('/dump/post', {
      baz: 'post',
    })
  }

  const putMethod = () => {
    router.put('/dump/put', {
      foo: 'put',
    })
  }

  const patchMethod = () => {
    router.patch('/dump/patch', {
      bar: 'patch',
    })
  }

  const deleteMethod = () => {
    router.delete('/dump/delete', {
      data: { baz: 'delete' },
    })
  }

  const qsafDefault = () => {
    router.visit('/dump/get', {
      data: { a: ['b', 'c'] },
    })
  }

  const qsafIndices = () => {
    router.visit('/dump/get', {
      data: { a: ['b', 'c'] },
      queryStringArrayFormat: 'indices',
    })
  }

  const qsafBrackets = () => {
    router.visit('/dump/get', {
      data: { a: ['b', 'c'] },
      queryStringArrayFormat: 'brackets',
    })
  }

  const deleteQueryParam = (e) => {
    e.preventDefault()
    router.visit('/dump/get', {
      data: { a: undefined },
    })
  }
</script>

<div>
  <span class="text">This is the page that demonstrates manual visit data passing through plain objects</span>

  <a href="#" on:click={visitMethod} class="visit">Visit Link</a>
  <a href="#" on:click={getMethod} class="get">GET Link</a>
  <a href="#" on:click={postMethod} class="post">POST Link</a>
  <a href="#" on:click={putMethod} class="put">PUT Link</a>
  <a href="#" on:click={patchMethod} class="patch">PATCH Link</a>
  <a href="#" on:click={deleteMethod} class="delete">DELETE Link</a>

  <a href="#" on:click={qsafDefault} class="qsaf-default">QSAF Defaults</a>
  <a href="#" on:click={qsafIndices} class="qsaf-indices">QSAF Indices</a>
  <a href="#" on:click={qsafBrackets} class="qsaf-brackets">QSAF Brackets</a>
  <a href="#" on:click={deleteQueryParam} class="delete-query-param">Delete Query Param</a>
</div>
