// packages/react/test-app/Pages/FormHelper/TypeScript/NullableNestedObject.tsx
// This component is used for checking the TypeScript implementation; there is no Playwright test depending on it.
import { useForm } from '@inertiajs/react'

interface FormData {
  foo: null | {
    bar: string
  }
}

export default function NullableNestedObject() {
  const form = useForm<FormData>({
    foo: null,
  })

  console.log(form.errors['foo.bar'])

  return <div></div>
}

// packages/svelte/test-app/Pages/FormHelper/TypeScript/NullableNestedObject.svelte
<script lang="ts">
  // This component is used for checking the TypeScript implementation; there is no Playwright test depending on it.
  import { useForm } from '@inertiajs/svelte'

  interface FormData {
    foo: null | {
      bar: string
    }
  }

  const form = useForm<FormData>({
    foo: null,
  })

  console.log($form.errors['foo.bar'])
</script>
