// packages/vue3/test-app/Pages/InfiniteScroll/ShortContent.vue
<script setup lang="ts">
import { InfiniteScroll } from '@inertiajs/vue3'
import { User } from './UserCard.vue'

defineProps<{
  users: { data: User[] }
}>()
</script>

<template>
  <InfiniteScroll data="users" items-element="tbody" #default="{ loadingPrevious, loadingNext }">
    <table style="width: 100%; border-collapse: collapse">
      <tbody>
        <tr v-for="user in users.data" :key="user.id" :data-user-id="user.id">
          <td style="padding: 10px; border: 1px solid #ccc">{{ user.id }}</td>
          <td style="padding: 10px; border: 1px solid #ccc">{{ user.name }}</td>
        </tr>
      </tbody>
    </table>
  </InfiniteScroll>
</template>

// packages/react/test-app/Pages/InfiniteScroll/ShortContent.tsx
import { InfiniteScroll } from '@inertiajs/react'
import { User } from './UserCard'

export default ({ users }: { users: { data: User[] } }) => {
  return (
    <InfiniteScroll data="users" slotElement="tbody">
      {({ loadingPrevious, loadingNext }) => (
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <tbody>
            {users.data.map((user) => (
              <tr key={user.id} data-user-id={user.id}>
                <td style={{ padding: '10px', border: '1px solid #ccc' }}>{user.id}</td>
                <td style={{ padding: '10px', border: '1px solid #ccc' }}>{user.name}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </InfiniteScroll>
  )
}
