// packages/vue3/test-app/Pages/InfiniteScroll/TriggerEndBuffer.vue
<script setup lang="ts">
import { InfiniteScroll } from '@inertiajs/vue3'
import { User, default as UserCard } from './UserCard.vue'

defineProps<{
  users: { data: User[] }
}>()
</script>

<template>
  <InfiniteScroll data="users" :buffer="200" trigger="end" style="display: grid; gap: 20px">
    <UserCard v-for="user in users.data" :key="user.id" :user="user" />

    <template #loading>
      <div style="text-align: center; padding: 20px">Loading...</div>
    </template>
  </InfiniteScroll>
</template>

// packages/react/test-app/Pages/InfiniteScroll/TriggerEndBuffer.tsx
import { InfiniteScroll } from '@inertiajs/react'
import UserCard, { User } from './UserCard'

export default ({ users }: { users: { data: User[] } }) => {
  return (
    <InfiniteScroll
      data="users"
      buffer={200}
      trigger="end"
      style={{ display: 'grid', gap: '20px' }}
      loading={() => <div style={{ textAlign: 'center', padding: '20px' }}>Loading...</div>}
    >
      {users.data.map((user) => (
        <UserCard key={user.id} user={user} />
      ))}
    </InfiniteScroll>
  )
}
