// packages/svelte5/test-app/Pages/InfiniteScroll/UserCard.svelte
<script module lang="ts">
  export interface User {
    id: number
    name: string
  }
</script>

<script lang="ts">
  interface Props {
    user: User;
  }

  let { user }: Props = $props();
</script>

<div
  data-user-id={user.id}
  style:height="15vh"
  style:border="1px solid #ccc"
  style:background-color={`rgba(150,150,150,${user.id / 40})`}
  style:color="green"
  style:display="flex"
  style:align-items="center"
  style:justify-content="center"
>
  {user.name}
</div>

// packages/react/test-app/Pages/InfiniteScroll/UserCard.tsx
export interface User {
  id: number
  name: string
}

export default ({ user }: { user: User }) => {
  return (
    <div
      data-user-id={user.id}
      style={{
        height: '15vh',
        border: '1px solid #ccc',
        backgroundColor: `rgba(150,150,150,${user.id / 40})`,
        color: 'green',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      }}
    >
      {user.name}
    </div>
  )
}
