// packages/react/test-app/Pages/Prefetch/NavigateEvent.tsx
import { Link, router } from '@inertiajs/react'
import { useEffect } from 'react'

export default () => {
  useEffect(() => {
    router.on('navigate', (event) => {
      console.log(String(event.detail.cached))
    })
  }, [])

  return (
    <>
      <Link href="/prefetch/navigate-event/cached" prefetch="mount">
        Prefetched Link
      </Link>
      <Link href="/prefetch/navigate-event/fresh">Regular Link</Link>
    </>
  )
}

// packages/vue3/test-app/Pages/Prefetch/NavigateEvent.vue
<script setup lang="ts">
import { Link, router } from '@inertiajs/vue3'
import { onMounted } from 'vue'

onMounted(() => {
  router.on('navigate', (event) => {
    console.log(String(event.detail.cached))
  })
})
</script>

<template>
  <Link href="/prefetch/navigate-event/cached" prefetch="mount">Prefetched Link</Link>
  <Link href="/prefetch/navigate-event/fresh">Regular Link</Link>
</template>
