// packages/react/test-app/Components/ClientOnlyChild.tsx
import { useEffect, useState } from 'react'

const ClientOnlyChild = () => {
  const [status, setStatus] = useState<'pending' | 'ready'>('pending')
  const [count, setCount] = useState(0)

  useEffect(() => {
    window._inertia_client_only_child_mounts = (window._inertia_client_only_child_mounts || 0) + 1

    const timer = setTimeout(() => setStatus('ready'), 100)

    return () => clearTimeout(timer)
  }, [])

  return (
    <div>
      <span data-testid="child-status">{status}</span>
      <span data-testid="child-count">{count}</span>
      <button data-testid="child-increment" onClick={() => setCount((c) => c + 1)}>
        Increment
      </button>
    </div>
  )
}

export default ClientOnlyChild

// packages/vue3/test-app/Components/ClientOnlyChild.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'

const status = ref<'pending' | 'ready'>('pending')
const count = ref(0)

let timer: ReturnType<typeof setTimeout>

onMounted(() => {
  window._inertia_client_only_child_mounts = (window._inertia_client_only_child_mounts || 0) + 1

  timer = setTimeout(() => {
    status.value = 'ready'
  }, 100)
})

onUnmounted(() => {
  clearTimeout(timer)
})
</script>

<template>
  <div>
    <span data-testid="child-status">{{ status }}</span>
    <span data-testid="child-count">{{ count }}</span>
    <button data-testid="child-increment" @click="count++">Increment</button>
  </div>
</template>
