// packages/react/test-app/Pages/InfiniteScroll/Manual.tsx
import { InfiniteScroll } from '@inertiajs/react'
import UserCard, { User } from './UserCard'

export default ({ users }: { users: { data: User[] } }) => {
  return (
    <InfiniteScroll
      data="users"
      style={{ display: 'grid', gap: '20px' }}
      manual
      previous={({ loading, fetch, hasMore }) => (
        <>
          <p>Has more previous items: {hasMore.toString()}</p>
          <button onClick={fetch}>{loading ? 'Loading previous items...' : 'Load previous items'}</button>
        </>
      )}
      next={({ loading, fetch, hasMore }) => (
        <>
          <p>Has more next items: {hasMore.toString()}</p>
          <button onClick={fetch}>{loading ? 'Loading next items...' : 'Load next items'}</button>
        </>
      )}
    >
      {users.data.map((user) => (
        <UserCard key={user.id} user={user} />
      ))}
    </InfiniteScroll>
  )
}

// packages/svelte5/test-app/Pages/InfiniteScroll/Manual.svelte
<script lang="ts">
  import { InfiniteScroll } from '@inertiajs/svelte5'
  import UserCard, { type User } from './UserCard.svelte'

  interface Props {
    users: { data: User[] };
  }

  let { users }: Props = $props();
</script>

<InfiniteScroll data="users" style="display: grid; gap: 20px" manual>
  {#snippet previous({ hasMore, loading, fetch })}
    <div    >
      <p>Has more previous items: {hasMore}</p>
      <button onclick={fetch}>
        {loading ? 'Loading previous items...' : 'Load previous items'}
      </button>
    </div>
  {/snippet}

  {#each users.data as user (user.id)}
    <UserCard {user} />
  {/each}

  {#snippet next({ hasMore, loading, fetch })}
    <div    >
      <p>Has more next items: {hasMore}</p>
      <button onclick={fetch}>
        {loading ? 'Loading next items...' : 'Load next items'}
      </button>
    </div>
  {/snippet}
</InfiniteScroll>
