// packages/react/test-app/Pages/FormHelper/Dirty.tsx
import { useForm } from '@inertiajs/react'

export default () => {
  const form = useForm({ name: 'foo', foo: [] as string[] })

  const submit = () => {
    form.post('')
  }

  const defaults = () => {
    form.setDefaults()
  }

  const dataAndDefaults = () => {
    pushValue()
    defaults()
  }

  const pushValue = () => {
    form.setData('foo', [...form.data.foo, 'bar'])
  }

  const submitAndSetDefaults = () => {
    form.post('/form-helper/dirty/redirect-back', {
      onSuccess: () => form.setDefaults(),
    })
  }

  const submitAndSetCustomDefaults = () => {
    form.post('/form-helper/dirty/redirect-back', {
      onSuccess: () => form.setDefaults({ name: 'Custom Default', foo: [] }),
    })
  }

  return (
    <div>
      <div>Form is {form.isDirty ? 'dirty' : 'clean'}</div>
      <label>
        Full Name
        <input
          type="text"
          id="name"
          name="name"
          onChange={(e) => form.setData('name', e.target.value)}
          value={form.data.name}
        />
      </label>

      <button onClick={submit} className="submit">
        Submit form
      </button>

      <button onClick={defaults} className="defaults">
        Defaults
      </button>

      <button onClick={dataAndDefaults} className="data-and-defaults">
        Data and Defaults
      </button>

      <button onClick={pushValue}>Push Value</button>

      <button onClick={submitAndSetDefaults} className="submit-and-set-defaults">
        Submit and setDefaults
      </button>

      <button onClick={submitAndSetCustomDefaults} className="submit-and-set-custom-defaults">
        Submit and setDefaults custom
      </button>
    </div>
  )
}

// packages/svelte/test-app/Pages/FormHelper/Dirty.svelte
<script lang="ts">
  import { useForm } from '@inertiajs/svelte'

  const form = useForm({
    name: 'foo',
    foo: [] as string[],
  })

  const submit = () => {
    form.post('')
  }

  const defaults = () => {
    form.defaults()
  }

  const pushValue = () => {
    form.foo.push('bar')
  }

  const dataAndDefaults = () => {
    pushValue()
    defaults()
  }

  const submitAndSetDefaults = () => {
    form.post('/form-helper/dirty/redirect-back', {
      onSuccess: () => form.defaults(),
    })
  }

  const submitAndSetCustomDefaults = () => {
    form.post('/form-helper/dirty/redirect-back', {
      onSuccess: () => form.defaults({ name: 'Custom Default', foo: [] }),
    })
  }
</script>

<div>
  <div>
    Form is {#if form.isDirty}dirty{:else}clean{/if}
  </div>
  <label>
    Full Name
    <input type="text" id="name" name="name" bind:value={form.name} />
  </label>

  <button onclick={submit} class="submit">Submit form</button>
  <button onclick={defaults} class="defaults">Defaults</button>
  <button onclick={dataAndDefaults} class="data-and-defaults">Data and Defaults</button>
  <button onclick={pushValue} class="push">Push value</button>

  <button onclick={submitAndSetDefaults} class="submit-and-set-defaults"> Submit and setDefaults </button>

  <button onclick={submitAndSetCustomDefaults} class="submit-and-set-custom-defaults">
    Submit and setDefaults custom
  </button>
</div>
