// packages/vue3/test-app/Pages/FormHelper/ErrorsClearOnResubmit.vue
<script setup lang="ts">
import { useForm } from '@inertiajs/vue3'

const form = useForm({
  name: '',
  handle: '',
})

const submit = () => {
  form.post('/form-helper/errors/clear-on-resubmit')
}
</script>

<template>
  <div>
    <label>
      Name
      <input type="text" id="name" name="name" v-model="form.name" />
    </label>
    <span id="name-error" v-if="form.errors.name">{{ form.errors.name }}</span>

    <label>
      Handle
      <input type="text" id="handle" name="handle" v-model="form.handle" />
    </label>
    <span id="handle-error" v-if="form.errors.handle">{{ form.errors.handle }}</span>

    <button @click="submit" id="submit">Submit</button>

    <span class="errors-status">Form has {{ form.hasErrors ? '' : 'no ' }}errors</span>
  </div>
</template>

// packages/svelte/test-app/Pages/FormHelper/ErrorsClearOnResubmit.svelte
<script lang="ts">
  import { useForm } from '@inertiajs/svelte'

  const form = useForm({
    name: '',
    handle: '',
  })

  const submit = () => {
    $form.post('/form-helper/errors/clear-on-resubmit')
  }
</script>

<div>
  <label>
    Name
    <input type="text" id="name" name="name" bind:value={$form.name} />
  </label>
  {#if $form.errors.name}
    <span id="name-error">{$form.errors.name}</span>
  {/if}

  <label>
    Handle
    <input type="text" id="handle" name="handle" bind:value={$form.handle} />
  </label>
  {#if $form.errors.handle}
    <span id="handle-error">{$form.errors.handle}</span>
  {/if}

  <button on:click={submit} id="submit">Submit</button>

  <span class="errors-status">Form has {$form.hasErrors ? '' : 'no '}errors</span>
</div>
