// packages/react/test-app/Pages/FormHelper/Transform.jsx
import { useForm } from '@inertiajs/react'

export default (props) => {
  const form = useForm({ name: 'foo', remember: false })

  const postForm = () => {
    form.transform((data) => ({ ...data, name: 'bar' }))
    form.post('/dump/post')
  }

  const putForm = () => {
    form.transform((data) => ({ ...data, name: 'baz' }))
    form.put('/dump/put')
  }

  const patchForm = () => {
    form.transform((data) => ({ ...data, name: 'foo' }))
    form.patch('/dump/patch')
  }

  const deleteForm = () => {
    form.transform((data) => ({ ...data, name: 'bar' }))
    form.delete('/dump/delete')
  }

  return (
    <div>
      <label>
        Full Name
        <input
          type="text"
          id="name"
          name="name"
          onChange={(e) => form.setData('name', e.target.value)}
          value={form.name}
        />
      </label>
      <label>
        Remember Me
        <input
          type="checkbox"
          id="remember"
          name="remember"
          onChange={(e) => form.setData('remember', e.target.checked)}
          value={form.remember}
        />
      </label>

      <button onClick={postForm} className="post">
        POST form
      </button>
      <button onClick={putForm} className="put">
        PUT form
      </button>
      <button onClick={patchForm} className="patch">
        PATCH form
      </button>
      <button onClick={deleteForm} className="delete">
        DELETE form
      </button>
    </div>
  )
}

// packages/svelte/test-app/Pages/FormHelper/Transform.svelte
<script>
  import { useForm } from '@inertiajs/svelte'

  const form = useForm({
    name: 'foo',
    remember: false,
  })

  const postForm = () => {
    $form
      .transform((data) => ({
        ...data,
        name: 'bar',
      }))
      .post('/dump/post')
  }

  const putForm = () => {
    $form
      .transform((data) => ({
        ...data,
        name: 'baz',
      }))
      .put('/dump/put')
  }

  const patchForm = () => {
    $form
      .transform((data) => ({
        ...data,
        name: 'foo',
      }))
      .patch('/dump/patch')
  }

  const deleteForm = () => {
    $form
      .transform((data) => ({
        ...data,
        name: 'bar',
      }))
      .delete('/dump/delete')
  }
</script>

<div>
  <label>
    Full Name
    <input type="text" id="name" name="name" bind:value={$form.name} />
  </label>
  <label>
    Remember Me
    <input type="checkbox" id="remember" name="remember" bind:checked={$form.remember} />
  </label>

  <button on:click={postForm} class="post">POST form</button>
  <button on:click={putForm} class="put">PUT form</button>
  <button on:click={patchForm} class="patch">PATCH form</button>
  <button on:click={deleteForm} class="delete">DELETE form</button>
</div>
