// packages/react/test-app/Pages/InfiniteScroll/Grid.tsx
import { InfiniteScroll } from '@inertiajs/react'
import UserCard, { User } from './UserCard'

export default ({ users }: { users: { data: User[] } }) => {
  return (
    <InfiniteScroll
      data="users"
      style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '20px' }}
      loading={() => (
        <div style={{ gridColumn: '1 / -1', textAlign: 'center', padding: '20px' }}>Loading more users...</div>
      )}
    >
      {() => users.data.map((user) => <UserCard key={user.id} user={user} />)}
    </InfiniteScroll>
  )
}

// packages/vue3/test-app/Pages/InfiniteScroll/Grid.vue
<script setup lang="ts">
import { InfiniteScroll } from '@inertiajs/vue3'
import { User, default as UserCard } from './UserCard.vue'

defineProps<{
  users: { data: User[] }
}>()
</script>

<template>
  <InfiniteScroll data="users" style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px">
    <UserCard v-for="user in users.data" :key="user.id" :user="user" />

    <template #loading>
      <div style="grid-column: 1 / -1; text-align: center; padding: 20px">Loading more users...</div>
    </template>
  </InfiniteScroll>
</template>
