// packages/svelte/test-app/Pages/InfiniteScroll/NavigateAway.svelte
<script lang="ts">
  import { inertia, InfiniteScroll } from '@inertiajs/svelte'
  import UserCard, { type User } from './UserCard.svelte'

  interface Props {
    users: { data: User[] }
  }

  let { users }: Props = $props()
</script>

<div>
  <a href="/article" id="leave" use:inertia>Leave to /article</a>
  <a href="/infinite-scroll/navigate-away/slow-article" id="leave-slowly" use:inertia>Leave slowly to /article</a>
  <a href="/infinite-scroll/navigate-away?order=desc" id="sort-slowly" use:inertia>Slowly sort descending</a>
  <InfiniteScroll data="users" style="display: grid; gap: 20px">
    {#snippet loading()}
      <div style="text-align: center; padding: 20px">Loading...</div>
    {/snippet}

    {#each users.data as user (user.id)}
      <UserCard {user} />
    {/each}
  </InfiniteScroll>
</div>

// packages/vue3/test-app/Pages/InfiniteScroll/NavigateAway.vue
<script setup lang="ts">
import { InfiniteScroll, Link } from '@inertiajs/vue3'
import { User, default as UserCard } from './UserCard.vue'

defineProps<{
  users: { data: User[] }
}>()
</script>

<template>
  <div>
    <Link href="/article" id="leave">Leave to /article</Link>
    <Link href="/infinite-scroll/navigate-away/slow-article" id="leave-slowly">Leave slowly to /article</Link>
    <Link href="/infinite-scroll/navigate-away?order=desc" id="sort-slowly">Slowly sort descending</Link>
    <InfiniteScroll data="users" style="display: grid; gap: 20px">
      <UserCard v-for="user in users.data" :key="user.id" :user="user" />

      <template #loading>
        <div style="text-align: center; padding: 20px">Loading...</div>
      </template>
    </InfiniteScroll>
  </div>
</template>
