// packages/svelte/test-app/Pages/InfiniteScroll/OverflowX.svelte
<script lang="ts">
  import { InfiniteScroll } from '@inertiajs/svelte'
  import type { User } from './UserCard.svelte'

  export let users: { data: User[] }
</script>

<div style="overflow-x: hidden">
  <InfiniteScroll data="users">
    {#each users.data as user (user.id)}
      <div data-user-id={user.id}>
        <div>{user.name}</div>
      </div>
    {/each}
  </InfiniteScroll>
</div>

// packages/vue3/test-app/Pages/InfiniteScroll/OverflowX.vue
<script setup lang="ts">
import { InfiniteScroll } from '@inertiajs/vue3'
import { User } from './UserCard.vue'

defineProps<{
  users: { data: User[] }
}>()
</script>

<template>
  <div style="overflow-x: hidden">
    <InfiniteScroll data="users">
      <div v-for="user in users.data" :key="user.id" :data-user-id="user.id">
        <div>{{ user.name }}</div>
      </div>
    </InfiniteScroll>
  </div>
</template>
