// packages/svelte/test-app/Pages/FormComponent/Progress.svelte
<script>
  import { Form } from '@inertiajs/svelte'
  import { onMount, onDestroy } from 'svelte'

  let showProgress = undefined
  let nprogressVisible = false
  let nprogressAppearances = 0
  let observer = null

  function disableProgress() {
    showProgress = false
  }

  onMount(() => {
    observer = new MutationObserver(() => {
      const nprogressElement = document.querySelector('#nprogress')
      const nprogressIsCurrentlyVisible = nprogressElement && nprogressElement.style.display !== 'none'

      if (nprogressIsCurrentlyVisible) {
        if (!nprogressVisible) {
          nprogressVisible = true
          nprogressAppearances = nprogressAppearances + 1
        }
      } else {
        nprogressVisible = false
      }
    })

    observer.observe(document.body, { childList: true, subtree: true })
  })

  onDestroy(() => {
    if (observer) {
      observer.disconnect()
    }
  })
</script>

<Form action="/form-component/progress" method="post" {showProgress}>
  <h1>Progress</h1>

  <div>
    Nprogress appearances: <span id="nprogress-appearances">{nprogressAppearances}</span>
  </div>

  <div>
    <button type="button" on:click={disableProgress}>Disable Progress</button>
    <button type="submit">Submit</button>
  </div>
</Form>

// packages/react/test-app/Pages/FormComponent/Progress.jsx
import { useEffect, useRef, useState } from 'react'
import { Form } from '@inertiajs/react'

export default () => {
  const [showProgress, setShowProgress] = useState(undefined)
  const [nprogressVisible, setNprogressVisible] = useState(false)
  const [nprogressAppearances, setNprogressAppearances] = useState(0)

  const observerRef = useRef(null)


  function disableProgress() {
    setShowProgress(false)
  }

  useEffect(() => {
    observerRef.current = new MutationObserver(() => {
      const nprogressElement = document.querySelector('#nprogress')
      const nprogressIsCurrentlyVisible = nprogressElement && nprogressElement.style.display !== 'none'

      if (nprogressIsCurrentlyVisible) {
        if (!nprogressVisible) {
          setNprogressVisible(true)
          setNprogressAppearances((previousCount) => previousCount + 1)
        }
      } else {
        setNprogressVisible(false)
      }
    })

    observerRef.current.observe(document.body, { childList: true, subtree: true })

    return () => observerRef.current?.disconnect()
  }, [])

  return (
    <Form action="/form-component/progress" method="post" showProgress={showProgress}>
      <h1>Progress</h1>

      <div>
        Nprogress appearances: <span id="nprogress-appearances">{nprogressAppearances}</span>
      </div>

      <div>
        <button type="button" onClick={disableProgress}>Disable Progress</button>
        <button type="submit">Submit</button>
      </div>
    </Form>
  )
}
