// packages/angular/src/lib/use-poll.ts
import { DestroyRef, afterNextRender, inject } from '@angular/core'
import { router, type PollOptions, type ReloadOptions } from '@inertiajs/core'

export function usePoll(
  interval: number,
  requestOptions: ReloadOptions | (() => ReloadOptions) = {},
  options: PollOptions = {},
): { stop: VoidFunction; start: VoidFunction } {
  const destroyRef = inject(DestroyRef)
  const autoStart = options.autoStart ?? true
  const poll = router.poll(interval, requestOptions, {
    ...options,
    autoStart: false,
  })

  afterNextRender(() => {
    if (autoStart) poll.start()
  })
  destroyRef.onDestroy(poll.destroy)

  return { stop: poll.stop, start: poll.start }
}

// packages/react/src/usePoll.ts
import { PollOptions, ReloadOptions, router } from '@inertiajs/core'
import { useEffect } from 'react'

export default function usePoll(interval: number, requestOptions: ReloadOptions = {}, options: PollOptions = {}) {
  const { stop, start } = router.poll(interval, requestOptions, {
    ...options,
    autoStart: false,
  })

  useEffect(() => {
    if (options.autoStart) {
      start()
    }

    return () => stop()
  }, [])

  return {
    stop,
    start,
  }
}
