// packages/svelte/test-app/Components/ClientOnlyChild.svelte
<script lang="ts">
  import { onMount } from 'svelte'

  let status = $state<'pending' | 'ready'>('pending')
  let count = $state(0)

  onMount(() => {
    window._inertia_client_only_child_mounts = (window._inertia_client_only_child_mounts || 0) + 1

    const timer = setTimeout(() => {
      status = 'ready'
    }, 100)

    return () => clearTimeout(timer)
  })
</script>

<div>
  <span data-testid="child-status">{status}</span>
  <span data-testid="child-count">{count}</span>
  <button data-testid="child-increment" onclick={() => count++}>Increment</button>
</div>

// packages/react/test-app/Components/ClientOnlyChild.tsx
import { useEffect, useState } from 'react'

const ClientOnlyChild = () => {
  const [status, setStatus] = useState<'pending' | 'ready'>('pending')
  const [count, setCount] = useState(0)

  useEffect(() => {
    window._inertia_client_only_child_mounts = (window._inertia_client_only_child_mounts || 0) + 1

    const timer = setTimeout(() => setStatus('ready'), 100)

    return () => clearTimeout(timer)
  }, [])

  return (
    <div>
      <span data-testid="child-status">{status}</span>
      <span data-testid="child-count">{count}</span>
      <button data-testid="child-increment" onClick={() => setCount((c) => c + 1)}>
        Increment
      </button>
    </div>
  )
}

export default ClientOnlyChild
