// packages/react/test-app/Pages/InfiniteScroll/TriggerStartBuffer.tsx
import { InfiniteScroll } from '@inertiajs/react'
import UserCard, { User } from './UserCard'

export default ({ users }: { users: { data: User[] } }) => {
  return (
    <InfiniteScroll
      data="users"
      buffer={200}
      trigger="start"
      style={{ display: 'grid', gap: '20px' }}
      loading={() => <div style={{ textAlign: 'center', padding: '20px' }}>Loading...</div>}
    >
      {users.data.map((user) => (
        <UserCard key={user.id} user={user} />
      ))}
    </InfiniteScroll>
  )
}

// packages/svelte/test-app/Pages/InfiniteScroll/TriggerStartBuffer.svelte
<script lang="ts">
  import { InfiniteScroll } from '@inertiajs/svelte'
  import UserCard, { type User } from './UserCard.svelte'

  export let users: { data: User[] }
</script>

<InfiniteScroll data="users" buffer={200} trigger="start" style="display: grid; gap: 20px">
  <div slot="loading" style="text-align: center; padding: 20px">Loading...</div>

  {#each users.data as user (user.id)}
    <UserCard {user} />
  {/each}
</InfiniteScroll>
