// packages/vue3/test-app/Pages/Poll/HookManual.vue
<script setup lang="ts">
import { usePoll } from '@inertiajs/vue3'

const { start, stop, polling } = usePoll(
  500,
  {
    only: ['custom_prop'],
    onFinish() {
      console.log('hook poll finished')
    },
  },
  {
    autoStart: false,
  },
)
</script>

<template>
  <button @click="start">Start</button>
  <button @click="stop">Stop</button>
  <div>Polling: {{ polling ? 'yes' : 'no' }}</div>
</template>

// packages/react/test-app/Pages/Poll/HookManual.tsx
import { usePoll } from '@inertiajs/react'

export default () => {
  const { start, stop, polling } = usePoll(
    500,
    {
      only: ['custom_prop'],
      onFinish() {
        console.log('hook poll finished')
      },
    },
    {
      autoStart: false,
    },
  )

  return (
    <>
      <button onClick={start}>Start</button>
      <button onClick={stop}>Stop</button>
      <div>Polling: {polling ? 'yes' : 'no'}</div>
    </>
  )
}
