// packages/svelte5/test-app/Pages/Remember/Default.svelte
<script lang="ts">
  import { inertia } from '@inertiajs/svelte5'

  let name = ''
  let remember = false
  let untracked = ''
</script>

<div>
  <label>
    Full Name
    <input type="text" id="name" name="full_name" bind:value={name} />
  </label>
  <label>
    Remember Me
    <input type="checkbox" id="remember" name="remember" bind:checked={remember} />
  </label>
  <label>
    Untracked
    <input type="text" id="untracked" name="untracked" bind:value={untracked} />
  </label>

  <a href="/dump/get" use:inertia class="link">Navigate away</a>
</div>

// packages/react/test-app/Pages/Remember/Default.jsx
import { Link } from '@inertiajs/react'
import { ref } from 'vue'

export default (props) => {
  const name = ref('')
  const remember = ref(false)
  const untracked = ref('')

  return (
    <div>
      <label>
        Full Name
        <input type="text" id="name" name="full_name" v-model="name" />
      </label>
      <label>
        Remember Me
        <input type="checkbox" id="remember" name="remember" v-model="remember" />
      </label>
      <label>
        Untracked
        <input type="text" id="untracked" name="untracked" v-model="untracked" />
      </label>

      <Link href="/dump/get" className="link">
        Navigate away
      </Link>
    </div>
  )
}
