// packages/react/test-app/Pages/LayoutProps/Basic.tsx
import { Link, setLayoutProps } from '@inertiajs/react'
import { useState } from 'react'
import AppLayout from '../../Layouts/AppLayout'

const Basic = () => {
  const [sidebarVisible, setSidebarVisible] = useState(true)

  setLayoutProps({
    showSidebar: sidebarVisible,
  })

  return (
    <div>
      <h2>Basic Layout Props Page</h2>
      <p>This page demonstrates setting layout props dynamically.</p>

      <div>
        <button type="button" onClick={() => setSidebarVisible(!sidebarVisible)}>
          Toggle Sidebar
        </button>
        <span>Sidebar: {sidebarVisible ? 'visible' : 'hidden'}</span>
      </div>

      <div>
        <button type="button" onClick={() => setLayoutProps({ title: 'Updated Title' })}>
          Update Title
        </button>
      </div>

      <nav>
        <Link href="/layout-props/navigate">Go to Navigate Page</Link>
      </nav>
    </div>
  )
}

Basic.layout = [AppLayout, { title: 'Basic Layout Props', showSidebar: true }]

export default Basic

// packages/vue3/test-app/Pages/LayoutProps/Basic.vue
<script lang="ts">
import AppLayout from '@/Layouts/AppLayout.vue'

export default {
  layout: [AppLayout, { title: 'Basic Layout Props', showSidebar: true }],
}
</script>

<script setup lang="ts">
import { Link, setLayoutProps } from '@inertiajs/vue3'
import { ref, watch } from 'vue'

const sidebarVisible = ref(true)

function toggleSidebar() {
  sidebarVisible.value = !sidebarVisible.value
}

watch(
  sidebarVisible,
  (value) => {
    setLayoutProps({ showSidebar: value })
  },
  { immediate: true },
)
</script>

<template>
  <div>
    <h2>Basic Layout Props Page</h2>
    <p>This page demonstrates setting layout props dynamically.</p>

    <div>
      <button type="button" @click="toggleSidebar">Toggle Sidebar</button>
      <span>Sidebar: {{ sidebarVisible ? 'visible' : 'hidden' }}</span>
    </div>

    <div>
      <button type="button" @click="setLayoutProps({ title: 'Updated Title' })">Update Title</button>
    </div>

    <nav>
      <Link href="/layout-props/navigate">Go to Navigate Page</Link>
    </nav>
  </div>
</template>
