// packages/react/test-app/Pages/LayoutProps/CallbackAllFunctionProps.tsx
import { Link } from '@inertiajs/react'

const CallbackAllFunctionProps = () => {
  return (
    <div>
      <h2>Callback All Function Props Page</h2>

      <nav>
        <Link href="/layout-props/basic">Go to Basic Page</Link>
      </nav>
    </div>
  )
}

CallbackAllFunctionProps.layout = () => ({
  formatTitle: (name: string) => `Profile: ${name}`,
  formatDate: (date: string) => new Date(date).toLocaleDateString(),
})

export default CallbackAllFunctionProps

// packages/vue3/test-app/Pages/LayoutProps/CallbackAllFunctionProps.vue
<script setup lang="ts">
import { Link } from '@inertiajs/vue3'

defineOptions({
  layout: () => ({
    formatTitle: (name: string) => `Profile: ${name}`,
    formatDate: (date: string) => new Date(date).toLocaleDateString(),
  }),
})
</script>

<template>
  <div>
    <h2>Callback All Function Props Page</h2>

    <nav>
      <Link href="/layout-props/basic">Go to Basic Page</Link>
    </nav>
  </div>
</template>
