// packages/react/test-app/Pages/LayoutProps/PersistentA.tsx
import { Link } from '@inertiajs/react'
import AppLayout from '../../Layouts/AppLayout'
import ContentLayout from '../../Layouts/ContentLayout'

const PersistentA = () => {
  return (
    <div>
      <h2>Persistent Page A</h2>

      <nav>
        <Link href="/layout-props/persistent-b">Go to Page B</Link>
      </nav>
    </div>
  )
}

PersistentA.layout = {
  app: AppLayout,
  content: ContentLayout,
}
PersistentA.layoutProps = (layout: (...args: unknown[]) => void) => {
  layout({ title: 'Persistent Page A' })
  layout('content', { padding: 'lg' })
}

export default PersistentA

// packages/vue3/test-app/Pages/LayoutProps/PersistentA.vue
<script lang="ts">
import AppLayout from '@/Layouts/AppLayout.vue'
import ContentLayout from '@/Layouts/ContentLayout.vue'

export default {
  layout: {
    app: AppLayout,
    content: ContentLayout,
  },
  layoutProps: (layout: (...args: unknown[]) => void) => {
    layout({ title: 'Persistent Page A' })
    layout('content', { padding: 'lg' })
  },
}
</script>

<script setup lang="ts">
import { Link } from '@inertiajs/vue3'
</script>

<template>
  <div>
    <h2>Persistent Page A</h2>

    <nav>
      <Link href="/layout-props/persistent-b">Go to Page B</Link>
    </nav>
  </div>
</template>
