// packages/react/test-app/Pages/DeferredProps/BackButton/PageB.tsx
import { Deferred, Link, usePage } from '@inertiajs/react'

const Data = () => {
  const { data } = usePage<{ data?: string }>().props

  return data
}

export default () => {
  return (
    <>
      <Deferred data="data" fallback={<div>Loading data...</div>}>
        <Data />
      </Deferred>

      <Link href="/deferred-props/back-button/a">Go to Page A</Link>
    </>
  )
}

// packages/svelte/test-app/Pages/DeferredProps/BackButton/PageB.svelte
<script lang="ts">
  import { Deferred, inertia } from '@inertiajs/svelte'

  interface Props {
    data: string | undefined
  }

  let { data }: Props = $props()
</script>

<Deferred data="data">
  {#snippet fallback()}
    <div>Loading data...</div>
  {/snippet}
  {data}
</Deferred>

<a href="/deferred-props/back-button/a" use:inertia>Go to Page A</a>
