// packages/react/test-app/Pages/BigInt.tsx
import { router, useHttp } from '@inertiajs/react'
import { useState } from 'react'

export default ({
  safe,
  big,
  negative,
  nested,
  huge,
  collision,
  echoedType,
}: {
  safe: number
  big: bigint
  negative: bigint
  nested: { deep: bigint[] }
  huge: bigint
  collision?: any
  echoedType?: string
}) => {
  const loadReloadData = () => router.get('/bigint/reload')
  const loadCollisionData = () => router.get('/bigint/collision')
  const submitEcho = () => router.post('/bigint/echo', { value: 111222333444555666n })

  const http = useHttp({ value: 111222333444555666n })
  const [httpEcho, setHttpEcho] = useState<string | null>(null)
  const submitHttpEcho = () =>
    http
      .post('/api/bigint/echo')
      .then((response: any) => setHttpEcho(`${response.value} (${response.type})`))
      .catch((error: Error) => setHttpEcho(`error: ${error.message}`))

  return (
    <div>
      <p>
        safe: <span id="safe">{String(safe)}</span> (<span id="safe-type">{typeof safe}</span>)
      </p>
      <p>
        big: <span id="big">{String(big)}</span> (<span id="big-type">{typeof big}</span>)
      </p>
      <p>
        negative: <span id="negative">{String(negative)}</span>
      </p>
      <p>
        huge: <span id="huge">{String(huge)}</span>
      </p>
      <p>
        nested: <span id="nested">{nested.deep.map(String).join(',')}</span>
      </p>
      {collision && (
        <p>
          collision: <span id="collision">{typeof collision === 'object' ? collision.$bigint : String(collision)}</span>{' '}
          (<span id="collision-type">{typeof collision}</span>)
        </p>
      )}

      {echoedType && (
        <p>
          echoed type: <span id="echoed-type">{echoedType}</span>
        </p>
      )}

      <button onClick={loadReloadData}>Load reload data</button>
      <button onClick={loadCollisionData}>Load collision data</button>
      <button onClick={submitEcho}>Submit echo</button>
      <button onClick={submitHttpEcho}>Submit useHttp echo</button>

      {httpEcho && <p id="http-echo">{httpEcho}</p>}
    </div>
  )
}

// packages/vue3/test-app/Pages/BigInt.vue
<script setup lang="ts">
import { router, useHttp } from '@inertiajs/vue3'
import { computed, ref } from 'vue'

const props = defineProps<{
  safe: number
  big: bigint
  negative: bigint
  nested: { deep: bigint[] }
  huge: bigint
  collision?: any
  echoedType?: string
}>()

const collisionValue = computed(() =>
  typeof props.collision === 'object' ? props.collision.$bigint : String(props.collision),
)

const loadReloadData = () => router.get('/bigint/reload')

const loadCollisionData = () => router.get('/bigint/collision')

const submitEcho = () => router.post('/bigint/echo', { value: 111222333444555666n })

const http = useHttp({ value: 111222333444555666n })
const httpEcho = ref<string | null>(null)
const submitHttpEcho = () =>
  http
    .post('/api/bigint/echo')
    .then((response: any) => (httpEcho.value = `${response.value} (${response.type})`))
    .catch((error: Error) => (httpEcho.value = `error: ${error.message}`))
</script>

<template>
  <div>
    <p>
      safe: <span id="safe">{{ safe }}</span> (<span id="safe-type">{{ typeof safe }}</span
      >)
    </p>
    <p>
      big: <span id="big">{{ big }}</span> (<span id="big-type">{{ typeof big }}</span
      >)
    </p>
    <p>
      negative: <span id="negative">{{ negative }}</span>
    </p>
    <p>
      huge: <span id="huge">{{ huge }}</span>
    </p>
    <p>
      nested: <span id="nested">{{ nested.deep.join(',') }}</span>
    </p>
    <p v-if="collision">
      collision: <span id="collision">{{ collisionValue }}</span> (<span id="collision-type">{{
        typeof collision
      }}</span
      >)
    </p>

    <p v-if="echoedType">
      echoed type: <span id="echoed-type">{{ echoedType }}</span>
    </p>

    <button @click="loadReloadData">Load reload data</button>
    <button @click="loadCollisionData">Load collision data</button>
    <button @click="submitEcho">Submit echo</button>
    <button @click="submitHttpEcho">Submit useHttp echo</button>

    <p v-if="httpEcho" id="http-echo">{{ httpEcho }}</p>
  </div>
</template>
