// packages/react/test-app/Pages/Dump.tsx
import { usePage } from '@inertiajs/react'
import { useEffect } from 'react'
import type { Method } from '@inertiajs/core'
import type { MulterFile } from '../types'

export default ({ headers, method, form, query, url, files }: { headers: Record<string, string>; method: Method; form: Record<string, unknown>; query: Record<string, unknown>; url: string; files: MulterFile[]|object }) => {
  const page = usePage()

  const dump = {
    headers,
    method,
    form,
    files: files ? files : {},
    query,
    url,
    $page: page,
  }

  useEffect(() => {
    window._inertia_request_dump = dump
  }, [])

  return (
    <div>
      <div className="text">This is Inertia page component containing a data dump of the request</div>
      <hr />
      <pre className="dump">{JSON.stringify(dump, null, 2)}</pre>
    </div>
  )
}

// packages/svelte/test-app/Pages/Dump.svelte
<script lang="ts">
  import type { Method } from '@inertiajs/core'
  import { page } from '@inertiajs/svelte'
  import { beforeUpdate } from 'svelte'
  import type { MulterFile } from '../types'

  export let headers: Record<string, string>
  export let method: Method
  export let form: Record<string, unknown>
  export let files: MulterFile[] | object = {}
  export let url: string
  export let query: Record<string, unknown>

  const dump = {
    headers,
    method,
    form,
    files,
    query,
    url,
    $page: $page,
  }

  beforeUpdate(() => {
    window._inertia_request_dump = dump
  })
</script>

<div>
  <div class="text">This is Inertia page component containing a data dump of the request</div>
  <hr />
  <pre class="dump" style="white-space: pre-wrap; word-break: keep-all;">{JSON.stringify(dump)}</pre>
</div>
