// packages/react/test-app/Pages/NetworkError.tsx
import { router } from '@inertiajs/react'
import { useEffect, useState } from 'react'

export default () => {
  const [error, setError] = useState(false)

  useEffect(() => {
    return router.on('exception', () => {
      setError(true)
      return false
    })
  }, [])

  function makeRequest() {
    setError(false)
    router.get('/network-error')
  }

  return (
    <div>
      <h1>Network Error</h1>
      {error && <div id="network-error">Network error occurred</div>}
      <button id="make-request" onClick={makeRequest}>
        Make Request
      </button>
    </div>
  )
}

// packages/svelte/test-app/Pages/NetworkError.svelte
<script lang="ts">
  import { router } from '@inertiajs/svelte'
  import { onMount } from 'svelte'

  let error = false

  onMount(() => {
    return router.on('exception', () => {
      error = true
      return false
    })
  })

  function makeRequest() {
    error = false
    router.get('/network-error')
  }
</script>

<div>
  <h1>Network Error</h1>
  {#if error}
    <div id="network-error">Network error occurred</div>
  {/if}
  <button id="make-request" on:click={makeRequest}>Make Request</button>
</div>
