// packages/react/test-app/Pages/FormHelper/Child.tsx
import type { InertiaFormProps } from '@inertiajs/react'

interface ChildProps {
  form: InertiaFormProps<{
    name: string
    email?: string
  }>
}

export default function Child({ form }: ChildProps) {
  return (
    <div>
      <p>Name: {form.data.name}</p>
      <p>Email: {form.data.email}</p>
    </div>
  )
}

// packages/vue3/test-app/Pages/FormHelper/Child.vue
<script setup lang="ts">
import type { InertiaForm } from '@inertiajs/vue3'
import { toRef } from 'vue'

const props = defineProps<{
  form: InertiaForm<{
    name: string
    email?: string
  }>
}>()

const form = toRef(props, 'form')
</script>

<template>
  <p>Name: {{ form.name }}</p>
  <p>Email: {{ form.email }}</p>
</template>
