// packages/vue3/test-app/Pages/FormComponent/Precognition/WithoutAllErrors.vue
<script setup lang="ts">
import { Form } from '@inertiajs/vue3'
</script>

<template>
  <div>
    <h1>Form Precognition - Array Errors</h1>

    <Form
      action="/precognition/with-all-errors"
      method="post"
      :validate-timeout="100"
      #default="{ invalid, errors, validate, valid, validating }"
    >
      <div>
        <input name="name" placeholder="Name" @blur="validate('name')" />
        <p v-if="invalid('name')">
          {{ errors.name }}
        </p>
        <p v-if="valid('name')">Name is valid!</p>
      </div>

      <div>
        <input name="email" placeholder="Email" @blur="validate('email')" />
        <p v-if="invalid('email')">
          {{ errors.email }}
        </p>
        <p v-if="valid('email')">Email is valid!</p>
      </div>

      <p v-if="validating">Validating...</p>
    </Form>
  </div>
</template>

// packages/svelte/test-app/Pages/FormComponent/Precognition/WithoutAllErrors.svelte
<script lang="ts">
  import { Form } from '@inertiajs/svelte'
</script>

<div>
  <h1>Form Precognition - Array Errors</h1>

  <Form
    action="/precognition/with-all-errors"
    method="post"
    validateTimeout={100}
    let:invalid
    let:errors
    let:validate
    let:valid
    let:validating
  >
    <div>
      <input name="name" placeholder="Name" on:blur={() => validate('name')} />
      {#if invalid('name')}
        <p>{errors.name}</p>
      {/if}
      {#if valid('name')}
        <p>Name is valid!</p>
      {/if}
    </div>

    <div>
      <input name="email" placeholder="Email" on:blur={() => validate('email')} />
      {#if invalid('email')}
        <p>{errors.email}</p>
      {/if}
      {#if valid('email')}
        <p>Email is valid!</p>
      {/if}
    </div>

    {#if validating}
      <p>Validating...</p>
    {/if}
  </Form>
</div>
