// packages/react/test-app/Pages/PersistentLayouts/Shorthand/Nested/PageA.tsx
import NestedLayout from '@/Layouts/NestedLayout.jsx'
import SiteLayout from '@/Layouts/SiteLayout.jsx'
import { Link, usePage } from '@inertiajs/react'

const PageA = () => {
  window._inertia_page_props = usePage().props

  return (
    <div>
      <span className="text">Nested Persistent Layout - Page A</span>
      <Link href="/persistent-layouts/shorthand/nested/page-b">Page B</Link>
    </div>
  )
}

PageA.layout = [SiteLayout, NestedLayout]

export default PageA

// packages/vue3/test-app/Pages/PersistentLayouts/Shorthand/Nested/PageA.vue
<script lang="ts">
import NestedLayout from '@/Layouts/NestedLayout.vue'
import SiteLayout from '@/Layouts/SiteLayout.vue'

export default {
  layout: [SiteLayout, NestedLayout],
}
</script>

<script setup lang="ts">
import { Link, usePage } from '@inertiajs/vue3'
window._inertia_page_props = usePage().props
</script>

<template>
  <div>
    <span class="text">Nested Persistent Layout - Page A</span>
    <Link href="/persistent-layouts/shorthand/nested/page-b">Page B</Link>
  </div>
</template>
