// packages/react/test-app/Layouts/SSRLayout.tsx
import { useLayoutProps } from '@inertiajs/react'
import { ReactNode } from 'react'

export default function SSRLayout({ children }: { children: ReactNode }) {
  const layoutProps = useLayoutProps({
    title: 'Default Title',
  })

  return (
    <div className="ssr-layout">
      <h1 data-testid="layout-title">{layoutProps.title}</h1>
      {children}
    </div>
  )
}

// packages/svelte/test-app/Layouts/SSRLayout.svelte
<script lang="ts">
import { useLayoutProps } from '@inertiajs/svelte'
import type { Snippet } from 'svelte'

let { children }: { children: Snippet } = $props()

const layoutProps = useLayoutProps({
  title: 'Default Title',
})
</script>

<div class="ssr-layout">
  <h1 data-testid="layout-title">{layoutProps.title}</h1>
  {@render children()}
</div>
