// playgrounds/svelte5/resources/js/Pages/Form.svelte
<script module>
  export { default as layout } from '../Components/Layout.svelte'
</script>

<script>
  import { useForm } from '@inertiajs/svelte'

  let { appName } = $props()

  let form = useForm('NewUser', {
    name: '',
    company: '',
    role: '',
  })

  function submit(e) {
    e.preventDefault()
    form.post('/user')
  }
</script>

<svelte:head>
  <title>Form - {appName}</title>
</svelte:head>

<h1 class="text-3xl">Form</h1>

<form onsubmit={submit} class="mt-6 max-w-md space-y-4">
  {#if form.isDirty}
    <div class="my-5 rounded-sm border border-amber-100 bg-amber-50 p-3 text-amber-800">There are unsaved changes!</div>
  {/if}
  <div>
    <label class="block" for="name">Name:</label>
    <input
      type="text"
      bind:value={form.name}
      id="name"
      class="mt-1 w-full appearance-none rounded-sm border border-gray-200 px-2 py-1 shadow-xs"
    />
    {#if form.errors.name}
      <div class="mt-2 text-sm text-red-600">{form.errors.name}</div>
    {/if}
  </div>
  <div>
    <label class="block" for="company">Company:</label>
    <input
      type="text"
      bind:value={form.company}
      id="company"
      class="mt-1 w-full appearance-none rounded-sm border border-gray-200 px-2 py-1 shadow-xs"
    />
    {#if form.errors.company}
      <div class="mt-2 text-sm text-red-600">{form.errors.company}</div>
    {/if}
  </div>
  <div>
    <label class="block" for="role">Role:</label>
    <select
      bind:value={form.role}
      id="role"
      class="mt-1 w-full appearance-none rounded-sm border border-gray-200 px-2 py-1 shadow-xs"
    >
      <option></option>
      <option>User</option>
      <option>Admin</option>
      <option>Super</option>
    </select>
    {#if form.errors.role}
      <div class="mt-2 text-sm text-red-600">{form.errors.role}</div>
    {/if}
  </div>
  <div class="flex gap-4">
    <button type="submit" disabled={form.processing} class="rounded-sm bg-slate-800 px-6 py-2 text-white">
      Submit
    </button>
    <button type="button" onclick={() => form.reset()}>Reset</button>
  </div>
</form>

// playgrounds/react/resources/js/Pages/Form.tsx
import { Head, useForm } from '@inertiajs/react'
import Layout from '../Components/Layout'

const Form = () => {
  const form = useForm('NewUser', {
    name: '',
    company: '',
    role: '',
  })

  function submit(e) {
    e.preventDefault()
    form.post('/user')
  }

  return (
    <>
      <Head title="Form" />
      <h1 className="text-3xl">Form</h1>
      <form onSubmit={submit} className="mt-6 max-w-md space-y-4">
        {form.isDirty && (
          <div className="my-5 rounded-sm border border-amber-100 bg-amber-50 p-3 text-amber-800">
            There are unsaved changes!
          </div>
        )}
        <div>
          <label className="block" htmlFor="name">
            Name:
          </label>
          <input
            type="text"
            value={form.data.name}
            onChange={(e) => form.setData('name', e.target.value)}
            id="name"
            className="mt-1 w-full appearance-none rounded-sm border border-gray-200 px-2 py-1 shadow-xs"
          />
          {form.errors.name && <div className="mt-2 text-sm text-red-600">{form.errors.name}</div>}
        </div>
        <div>
          <label className="block" htmlFor="company">
            Company:
          </label>
          <input
            type="text"
            value={form.data.company}
            onChange={(e) => form.setData('company', e.target.value)}
            id="company"
            className="mt-1 w-full appearance-none rounded-sm border border-gray-200 px-2 py-1 shadow-xs"
          />
          {form.errors.company && <div className="mt-2 text-sm text-red-600">{form.errors.company}</div>}
        </div>
        <div>
          <label className="block" htmlFor="role">
            Role:
          </label>
          <select
            value={form.data.role}
            onChange={(e) => form.setData('role', e.target.value)}
            id="role"
            className="mt-1 w-full appearance-none rounded-sm border border-gray-200 px-2 py-1 shadow-xs"
          >
            <option></option>
            <option>User</option>
            <option>Admin</option>
            <option>Super</option>
          </select>
          {form.errors.role && <div className="mt-2 text-sm text-red-600">{form.errors.role}</div>}
        </div>
        <div className="flex gap-4">
          <button type="submit" disabled={form.processing} className="rounded-sm bg-slate-800 px-6 py-2 text-white">
            Submit
          </button>
          <button type="button" onClick={() => form.reset()}>
            Reset
          </button>
        </div>
      </form>
    </>
  )
}

Form.layout = Layout

export default Form
