// packages/svelte/test-app/Pages/FormHelper/Precognition/Cancel.svelte
<script lang="ts">
  import { useForm } from '@inertiajs/svelte'

  const form = useForm({
    name: '',
  })
    .withPrecognition('post', '/precognition/default?slow=1')
    .setValidationTimeout(100)
</script>

<div>
  <div>
    <input
      id="auto-cancel-name-input"
      bind:value={$form.name}
      name="name"
      placeholder="Name"
      on:blur={() => $form.validate('name')}
    />
    {#if $form.invalid('name')}
      <p>
        {$form.errors.name}
      </p>
    {/if}
    {#if $form.valid('name')}<p>Name is valid!</p>{/if}
  </div>

  {#if $form.validating}<p>Validating...</p>{/if}
</div>

// packages/vue3/test-app/Pages/FormHelper/Precognition/Cancel.vue
<script setup lang="ts">
import { useForm } from '@inertiajs/vue3'

const form = useForm({
  name: '',
})
  .withPrecognition('post', '/precognition/default?slow=1')
  .setValidationTimeout(100)
</script>

<template>
  <div>
    <div>
      <input
        id="auto-cancel-name-input"
        v-model="form.name"
        name="name"
        placeholder="Name"
        @blur="form.validate('name')"
      />
      <p v-if="form.invalid('name')">
        {{ form.errors.name }}
      </p>
      <p v-if="form.valid('name')">Name is valid!</p>
    </div>

    <p v-if="form.validating">Validating...</p>
  </div>
</template>
