// packages/svelte/test-app/Pages/FormHelper/Precognition/DynamicArrayInputs.svelte
<script lang="ts">
  import { useForm } from '@inertiajs/svelte'

  const form = useForm({
    items: [] as Array<{ name: string }>,
  })
    .withPrecognition('post', '/precognition/dynamic-array-inputs')
    .setValidationTimeout(100)

  function addItem() {
    $form.items = [...$form.items, { name: '' }]
  }
</script>

<div>
  <button id="add-item" on:click={addItem}>Add Item</button>

  {#each $form.items as item, idx}
    <div>
      <input bind:value={item.name} name={`items.${idx}.name`} on:blur={() => $form.validate(`items.${idx}.name`)} />
      {#if $form.invalid(`items.${idx}.name`)}<p id={`items.${idx}.name-error`}>{$form.errors[`items.${idx}.name`]}</p>{/if}
      {#if $form.valid(`items.${idx}.name`)}<p>Valid!</p>{/if}
    </div>
  {/each}

  {#if $form.validating}<p>Validating...</p>{/if}
</div>

// packages/vue3/test-app/Pages/FormHelper/Precognition/DynamicArrayInputs.vue
<script setup lang="ts">
import { useForm } from '@inertiajs/vue3'

const form = useForm({
  items: [] as Array<{ name: string }>,
})
  .withPrecognition('post', '/precognition/dynamic-array-inputs')
  .setValidationTimeout(100)

function addItem() {
  form.items.push({ name: '' })
}
</script>

<template>
  <div>
    <button id="add-item" @click="addItem">Add Item</button>

    <div v-for="(item, idx) in form.items" :key="idx">
      <input v-model="item.name" :name="`items.${idx}.name`" @blur="form.validate(`items.${idx}.name`)" />
      <p v-if="form.invalid(`items.${idx}.name`)" :id="`items.${idx}.name-error`">
        {{ form.errors[`items.${idx}.name`] }}
      </p>
      <p v-if="form.valid(`items.${idx}.name`)">Valid!</p>
    </div>

    <p v-if="form.validating">Validating...</p>
  </div>
</template>
