// packages/vue3/test-app/Pages/SSR/InfiniteScroll.vue
<script setup lang="ts">
import { InfiniteScroll } from '@inertiajs/vue3'

defineProps<{
  users: { data: { id: number; name: string }[] }
}>()
</script>

<template>
  <div>
    <h1 data-testid="ssr-title">SSR Infinite Scroll</h1>

    <InfiniteScroll data="users" manual>
      <template #previous="{ hasMore }">
        <p data-testid="has-previous">Has previous: {{ hasMore }}</p>
      </template>

      <div v-for="user in users.data" :key="user.id" data-testid="user">
        {{ user.name }}
      </div>

      <template #next="{ hasMore }">
        <p data-testid="has-next">Has next: {{ hasMore }}</p>
      </template>
    </InfiniteScroll>
  </div>
</template>

// packages/react/test-app/Pages/SSR/InfiniteScroll.tsx
import { InfiniteScroll } from '@inertiajs/react'

export default ({ users }: { users: { data: { id: number; name: string }[] } }) => {
  return (
    <div>
      <h1 data-testid="ssr-title">SSR Infinite Scroll</h1>

      <InfiniteScroll
        data="users"
        manual
        previous={({ hasMore }) => <p data-testid="has-previous">Has previous: {hasMore.toString()}</p>}
        next={({ hasMore }) => <p data-testid="has-next">Has next: {hasMore.toString()}</p>}
      >
        {users.data.map((user) => (
          <div key={user.id} data-testid="user">
            {user.name}
          </div>
        ))}
      </InfiniteScroll>
    </div>
  )
}
