// packages/vue3/test-app/Pages/FormComponent/PrecognitionDefaults.vue
<script setup lang="ts">
import { Form } from '@inertiajs/vue3'
import { ref } from 'vue'

const formRef = ref()

const handleSetDefaults = () => {
  formRef.value.defaults()
}
</script>

<template>
  <div>
    <h1>Precognition - Defaults Updates Validator</h1>

    <Form
      ref="formRef"
      action="/form-component/precognition"
      method="post"
      :validate-timeout="100"
      #default="{ invalid, errors, validate, validating }"
    >
      <div>
        <input id="name-input" name="name" placeholder="Name" />
        <p v-if="invalid('name')" class="error">
          {{ errors.name }}
        </p>
      </div>

      <p v-if="validating" class="validating">Validating...</p>

      <button type="button" @click="handleSetDefaults">Set Defaults</button>
      <button type="button" @click="validate('name')">Validate Name</button>
      <button type="submit">Submit</button>
    </Form>
  </div>
</template>

// packages/svelte/test-app/Pages/FormComponent/PrecognitionDefaults.svelte
<script lang="ts">
  import { Form } from '@inertiajs/svelte'

  let formRef: any

  const handleSetDefaults = () => {
    formRef?.defaults()
  }
</script>

<div>
  <h1>Precognition - Defaults Updates Validator</h1>

  <Form
    bind:this={formRef}
    action="/form-component/precognition"
    method="post"
    validateTimeout={100}
    let:invalid
    let:errors
    let:validate
    let:validating
  >
    <div>
      <input id="name-input" name="name" placeholder="Name" />
      {#if invalid('name')}
        <p class="error">
          {errors.name}
        </p>
      {/if}
    </div>

    {#if validating}
      <p class="validating">Validating...</p>
    {/if}

    <button type="button" on:click={handleSetDefaults}>Set Defaults</button>
    <button type="button" on:click={() => validate('name')}>Validate Name</button>
    <button type="submit">Submit</button>
  </Form>
</div>
