// packages/react/test-app/Pages/FormComponent/Precognition/PrecognitionHeaders.tsx
import { Form } from '@inertiajs/react'

export default function PrecognitionHeaders() {
  return (
    <div>
      <h1>Precognition - Custom Headers</h1>

      <Form
        action="/precognition/headers"
        method="post"
        headers={{ 'X-Custom-Header': 'custom-value' }}
        validateTimeout={100}
      >
        {({ invalid, errors, validate, validating }) => (
          <>
            <div>
              <input name="name" placeholder="Name" onBlur={() => validate('name')} />
              {invalid('name') && <p>{errors.name}</p>}
            </div>

            {validating && <p>Validating...</p>}

            <button type="submit">Submit</button>
          </>
        )}
      </Form>
    </div>
  )
}

// packages/svelte/test-app/Pages/FormComponent/PrecognitionHeaders.svelte
<script lang="ts">
  import { Form } from '@inertiajs/svelte'
</script>

<div>
  <h1>Precognition - Custom Headers</h1>

  <Form
    action="/precognition/headers"
    method="post"
    headers={{ 'X-Custom-Header': 'custom-value' }}
    validateTimeout={100}
    let:invalid
    let:errors
    let:validate
    let:validating
  >
    <div>
      <input name="name" placeholder="Name" on:blur={() => validate('name')} />
      {#if invalid('name')}
        <p>
          {errors.name}
        </p>
      {/if}
    </div>

    {#if validating}
      <p>Validating...</p>
    {/if}

    <button type="submit">Submit</button>
  </Form>
</div>
