// packages/svelte/test-app/Pages/Links/Replace.svelte
<script lang="ts">
  import { inertia } from '@inertiajs/svelte'
</script>

<div>
  <span class="text">This is the links page that demonstrates replace on Links</span>

  <a href="/dump/get" use:inertia={{ replace: true }} class="replace">[State] Replace: true</a>
  <a href="/dump/get" use:inertia={{ replace: false }} class="replace-false">[State] Replace: false</a>
</div>

// packages/react/test-app/Pages/Links/Replace.jsx
import { Link } from '@inertiajs/react'

export default (props) => {
  return (
    <div>
      <span className="text">This is the links page that demonstrates replace on Links</span>

      <Link href="/dump/get" replace className="replace">
        [State] Replace: true
      </Link>
      <Link href="/dump/get" replace={false} className="replace-false">
        [State] Replace: false
      </Link>
    </div>
  )
}
