// packages/svelte/test-app/Pages/FormComponent/Precognition/Callbacks.svelte
<script lang="ts">
  import { Form } from '@inertiajs/svelte'

  let successCalled = false
  let errorCalled = false
  let finishCalled = false
</script>

<div>
  <h1>Form Precognition Callbacks</h1>

  <h2>Callbacks Test</h2>
  <Form action="/precognition/default" method="post" validationTimeout={100} let:validate let:validating let:touch>
    <div>
      <input name="name" placeholder="Name" on:blur={() => touch('name')} />
    </div>

    {#if validating}
      <p>Validating...</p>
    {/if}
    {#if successCalled}
      <p>onPrecognitionSuccess called!</p>
    {/if}
    {#if errorCalled}
      <p>onValidationError called!</p>
    {/if}
    {#if finishCalled}
      <p>onFinish called!</p>
    {/if}

    <button
      type="button"
      on:click={() => {
        successCalled = false
        errorCalled = false
        finishCalled = false
        validate({
          onPrecognitionSuccess: () => {
            successCalled = true
          },
          onValidationError: () => {
            errorCalled = true
          },
          onFinish: () => {
            finishCalled = true
          },
        })
      }}
    >
      Validate
    </button>
  </Form>
</div>

// packages/react/test-app/Pages/FormComponent/Precognition/Callbacks.tsx
import { Form } from '@inertiajs/react'
import { useState } from 'react'

export default () => {
  const [successCalled, setSuccessCalled] = useState(false)
  const [errorCalled, setErrorCalled] = useState(false)
  const [finishCalled, setFinishCalled] = useState(false)

  return (
    <div>
      <h1>Form Precognition Callbacks</h1>

      <h2>Callbacks Test</h2>
      <Form action="/precognition/default" method="post" validationTimeout={100}>
        {({ validate, validating, touch }) => (
          <>
            <div>
              <input name="name" placeholder="Name" onBlur={() => touch('name')} />
            </div>

            {validating && <p>Validating...</p>}
            {successCalled && <p>onPrecognitionSuccess called!</p>}
            {errorCalled && <p>onValidationError called!</p>}
            {finishCalled && <p>onFinish called!</p>}

            <button
              type="button"
              onClick={() => {
                setSuccessCalled(false)
                setErrorCalled(false)
                setFinishCalled(false)
                validate({
                  onPrecognitionSuccess: () => {
                    setSuccessCalled(true)
                  },
                  onValidationError: () => {
                    setErrorCalled(true)
                  },
                  onFinish: () => {
                    setFinishCalled(true)
                  },
                })
              }}
            >
              Validate
            </button>
          </>
        )}
      </Form>
    </div>
  )
}
