// packages/react/test-app/Pages/Head/Dataset.tsx
import { config, Head } from '@inertiajs/react'

export default () => {
  config.set('future.useDataSetInHeadManager', true)

  return (
    <>
      <Head title="Test Head Component">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <h1 style={{ fontSize: '40px' }}>Head Component</h1>
    </>
  )
}

// packages/vue3/test-app/Pages/Head/Dataset.vue
<script setup lang="ts">
import { config, Head } from '@inertiajs/vue3'

config.set('future.useDataSetInHeadManager', true)
</script>

<template>
  <Head title="Test Head Component">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </Head>

  <h1 :style="{ fontSize: '40px' }">Head Component</h1>
</template>
