// packages/react/test-app/Pages/DeferredProps/WithCallback.tsx
import { Deferred, Link, usePage } from '@inertiajs/react'

const Foo = () => {
  const { foo } = usePage<{ foo?: { text: string } }>().props

  return foo?.text
}

const Bar = () => {
  const { bar } = usePage<{ bar?: { text: string } }>().props

  return bar?.text
}

export default () => {
  return (
    <>
      <Deferred data="foo">{({ loading }) => (loading ? <div>Loading foo (callback)...</div> : <Foo />)}</Deferred>

      <Deferred data="bar">{({ loading }) => (loading ? <div>Loading bar (callback)...</div> : <Bar />)}</Deferred>

      <Link href="/deferred-props/page-1">Page 1</Link>
      <Link href="/deferred-props/page-2">Page 2</Link>
    </>
  )
}

// packages/vue3/test-app/Pages/DeferredProps/WithCallback.vue
<script setup lang="ts">
import { Deferred, Link } from '@inertiajs/vue3'

defineProps<{
  foo?: { text: string }
  bar?: { text: string }
}>()
</script>

<template>
  <Deferred data="foo">
    <template #default="{ loading }">
      <div v-if="loading">Loading foo (callback)...</div>
      <div v-else>{{ foo?.text }}</div>
    </template>
  </Deferred>

  <Deferred data="bar">
    <template #default="{ loading }">
      <div v-if="loading">Loading bar (callback)...</div>
      <div v-else>{{ bar?.text }}</div>
    </template>
  </Deferred>

  <Link href="/deferred-props/page-1">Page 1</Link>
  <Link href="/deferred-props/page-2">Page 2</Link>
</template>
