// packages/react/test-app/Pages/LayoutProps/CallbackStatic.tsx
import { Link } from '@inertiajs/react'

const CallbackStatic = () => {
  return (
    <div>
      <h2>Static Callback Layout Page</h2>

      <nav>
        <Link href="/layout-props/basic">Go to Basic Page</Link>
      </nav>
    </div>
  )
}

CallbackStatic.layout = () => ({
  title: 'Static Callback Title',
  showSidebar: false,
})

export default CallbackStatic

// packages/svelte/test-app/Pages/LayoutProps/CallbackStatic.svelte
<script module lang="ts">
  export const layout = () => ({
    title: 'Static Callback Title',
    showSidebar: false,
  })
</script>

<script lang="ts">
  import { Link } from '@inertiajs/svelte'
</script>

<div>
  <h2>Static Callback Layout Page</h2>

  <nav>
    <Link href="/layout-props/basic">Go to Basic Page</Link>
  </nav>
</div>
